//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dlubal.WS.Rstab9.Application
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dlubal.com", ConfigurationName="Dlubal.WS.Rstab9.Application.IRstabApplication")]
    [System.Xml.Serialization.XmlSerializerAssembly]
    public interface IRstabApplication
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8081/close_application", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dlubal.WS.Rstab9.Application.close_applicationResponse close_application(Dlubal.WS.Rstab9.Application.close_applicationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8081/close_model", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dlubal.WS.Rstab9.Application.close_modelResponse close_model(Dlubal.WS.Rstab9.Application.close_modelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8081/get_active_model", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dlubal.WS.Rstab9.Application.get_active_modelResponse get_active_model(Dlubal.WS.Rstab9.Application.get_active_modelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8081/get_information", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dlubal.WS.Rstab9.Application.get_informationResponse get_information(Dlubal.WS.Rstab9.Application.get_informationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8081/get_model", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dlubal.WS.Rstab9.Application.get_modelResponse get_model(Dlubal.WS.Rstab9.Application.get_modelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8081/get_model_list", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dlubal.WS.Rstab9.Application.get_model_listResponse get_model_list(Dlubal.WS.Rstab9.Application.get_model_listRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8081/new_model", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dlubal.WS.Rstab9.Application.new_modelResponse new_model(Dlubal.WS.Rstab9.Application.new_modelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8081/open_model", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Dlubal.WS.Rstab9.Application.open_modelResponse open_model(Dlubal.WS.Rstab9.Application.open_modelRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRstabApplicationChannel : Dlubal.WS.Rstab9.Application.IRstabApplication, System.ServiceModel.IClientChannel
    {
    }
}
