//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dlubal.WS.Rstab9.Application
{
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RstabApplicationClient : System.ServiceModel.ClientBase<Dlubal.WS.Rstab9.Application.IRstabApplication>, Dlubal.WS.Rstab9.Application.IRstabApplication
    {
        
        public RstabApplicationClient()
        {
        }
        
        public RstabApplicationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public RstabApplicationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RstabApplicationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RstabApplicationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.Rstab9.Application.close_applicationResponse Dlubal.WS.Rstab9.Application.IRstabApplication.close_application(Dlubal.WS.Rstab9.Application.close_applicationRequest request)
        {
            return base.Channel.close_application(request);
        }
        
        public void close_application()
        {
            Dlubal.WS.Rstab9.Application.close_applicationRequest inValue = new Dlubal.WS.Rstab9.Application.close_applicationRequest();
            Dlubal.WS.Rstab9.Application.close_applicationResponse retVal = ((Dlubal.WS.Rstab9.Application.IRstabApplication)(this)).close_application(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.Rstab9.Application.close_modelResponse Dlubal.WS.Rstab9.Application.IRstabApplication.close_model(Dlubal.WS.Rstab9.Application.close_modelRequest request)
        {
            return base.Channel.close_model(request);
        }
        
        public void close_model(int index, bool save_changes)
        {
            Dlubal.WS.Rstab9.Application.close_modelRequest inValue = new Dlubal.WS.Rstab9.Application.close_modelRequest();
            inValue.index = index;
            inValue.save_changes = save_changes;
            Dlubal.WS.Rstab9.Application.close_modelResponse retVal = ((Dlubal.WS.Rstab9.Application.IRstabApplication)(this)).close_model(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.Rstab9.Application.get_active_modelResponse Dlubal.WS.Rstab9.Application.IRstabApplication.get_active_model(Dlubal.WS.Rstab9.Application.get_active_modelRequest request)
        {
            return base.Channel.get_active_model(request);
        }
        
        public string get_active_model()
        {
            Dlubal.WS.Rstab9.Application.get_active_modelRequest inValue = new Dlubal.WS.Rstab9.Application.get_active_modelRequest();
            Dlubal.WS.Rstab9.Application.get_active_modelResponse retVal = ((Dlubal.WS.Rstab9.Application.IRstabApplication)(this)).get_active_model(inValue);
            return retVal.value;
        }
        
        public Dlubal.WS.Rstab9.Application.application_information get_information()
        {
            Dlubal.WS.Rstab9.Application.get_informationRequest inValue = new Dlubal.WS.Rstab9.Application.get_informationRequest();
            Dlubal.WS.Rstab9.Application.get_informationResponse retVal = ((Dlubal.WS.Rstab9.Application.IRstabApplication)(this)).get_information(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.Rstab9.Application.get_informationResponse Dlubal.WS.Rstab9.Application.IRstabApplication.get_information(Dlubal.WS.Rstab9.Application.get_informationRequest request)
        {
            return base.Channel.get_information(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.Rstab9.Application.get_modelResponse Dlubal.WS.Rstab9.Application.IRstabApplication.get_model(Dlubal.WS.Rstab9.Application.get_modelRequest request)
        {
            return base.Channel.get_model(request);
        }
        
        public string get_model(int index)
        {
            Dlubal.WS.Rstab9.Application.get_modelRequest inValue = new Dlubal.WS.Rstab9.Application.get_modelRequest();
            inValue.index = index;
            Dlubal.WS.Rstab9.Application.get_modelResponse retVal = ((Dlubal.WS.Rstab9.Application.IRstabApplication)(this)).get_model(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.Rstab9.Application.get_model_listResponse Dlubal.WS.Rstab9.Application.IRstabApplication.get_model_list(Dlubal.WS.Rstab9.Application.get_model_listRequest request)
        {
            return base.Channel.get_model_list(request);
        }
        
        public string[] get_model_list()
        {
            Dlubal.WS.Rstab9.Application.get_model_listRequest inValue = new Dlubal.WS.Rstab9.Application.get_model_listRequest();
            Dlubal.WS.Rstab9.Application.get_model_listResponse retVal = ((Dlubal.WS.Rstab9.Application.IRstabApplication)(this)).get_model_list(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.Rstab9.Application.new_modelResponse Dlubal.WS.Rstab9.Application.IRstabApplication.new_model(Dlubal.WS.Rstab9.Application.new_modelRequest request)
        {
            return base.Channel.new_model(request);
        }
        
        public string new_model(string model_name)
        {
            Dlubal.WS.Rstab9.Application.new_modelRequest inValue = new Dlubal.WS.Rstab9.Application.new_modelRequest();
            inValue.model_name = model_name;
            Dlubal.WS.Rstab9.Application.new_modelResponse retVal = ((Dlubal.WS.Rstab9.Application.IRstabApplication)(this)).new_model(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.Rstab9.Application.open_modelResponse Dlubal.WS.Rstab9.Application.IRstabApplication.open_model(Dlubal.WS.Rstab9.Application.open_modelRequest request)
        {
            return base.Channel.open_model(request);
        }
        
        public string open_model(string model_path)
        {
            Dlubal.WS.Rstab9.Application.open_modelRequest inValue = new Dlubal.WS.Rstab9.Application.open_modelRequest();
            inValue.model_path = model_path;
            Dlubal.WS.Rstab9.Application.open_modelResponse retVal = ((Dlubal.WS.Rstab9.Application.IRstabApplication)(this)).open_model(inValue);
            return retVal.value;
        }
    }
}
