//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dlubal.WS.RSection1.Model
{
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RSectionModelClient : System.ServiceModel.ClientBase<Dlubal.WS.RSection1.Model.IRSectionModel>, Dlubal.WS.RSection1.Model.IRSectionModel
    {
        
        public RSectionModelClient()
        {
        }
        
        public RSectionModelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public RSectionModelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RSectionModelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public RSectionModelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.begin_modificationResponse Dlubal.WS.RSection1.Model.IRSectionModel.begin_modification(Dlubal.WS.RSection1.Model.begin_modificationRequest request)
        {
            return base.Channel.begin_modification(request);
        }
        
        public void begin_modification(string modification_name)
        {
            Dlubal.WS.RSection1.Model.begin_modificationRequest inValue = new Dlubal.WS.RSection1.Model.begin_modificationRequest();
            inValue.modification_name = modification_name;
            Dlubal.WS.RSection1.Model.begin_modificationResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).begin_modification(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.calculate_allResponse Dlubal.WS.RSection1.Model.IRSectionModel.calculate_all(Dlubal.WS.RSection1.Model.calculate_allRequest request)
        {
            return base.Channel.calculate_all(request);
        }
        
        public void calculate_all(bool generateXmlSolverInput)
        {
            Dlubal.WS.RSection1.Model.calculate_allRequest inValue = new Dlubal.WS.RSection1.Model.calculate_allRequest();
            inValue.generateXmlSolverInput = generateXmlSolverInput;
            Dlubal.WS.RSection1.Model.calculate_allResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).calculate_all(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.cancel_modificationResponse Dlubal.WS.RSection1.Model.IRSectionModel.cancel_modification(Dlubal.WS.RSection1.Model.cancel_modificationRequest request)
        {
            return base.Channel.cancel_modification(request);
        }
        
        public void cancel_modification()
        {
            Dlubal.WS.RSection1.Model.cancel_modificationRequest inValue = new Dlubal.WS.RSection1.Model.cancel_modificationRequest();
            Dlubal.WS.RSection1.Model.cancel_modificationResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).cancel_modification(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.clear_selectionResponse Dlubal.WS.RSection1.Model.IRSectionModel.clear_selection(Dlubal.WS.RSection1.Model.clear_selectionRequest request)
        {
            return base.Channel.clear_selection(request);
        }
        
        public void clear_selection()
        {
            Dlubal.WS.RSection1.Model.clear_selectionRequest inValue = new Dlubal.WS.RSection1.Model.clear_selectionRequest();
            Dlubal.WS.RSection1.Model.clear_selectionResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).clear_selection(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.close_connectionResponse Dlubal.WS.RSection1.Model.IRSectionModel.close_connection(Dlubal.WS.RSection1.Model.close_connectionRequest request)
        {
            return base.Channel.close_connection(request);
        }
        
        public void close_connection()
        {
            Dlubal.WS.RSection1.Model.close_connectionRequest inValue = new Dlubal.WS.RSection1.Model.close_connectionRequest();
            Dlubal.WS.RSection1.Model.close_connectionResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).close_connection(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.delete_allResponse Dlubal.WS.RSection1.Model.IRSectionModel.delete_all(Dlubal.WS.RSection1.Model.delete_allRequest request)
        {
            return base.Channel.delete_all(request);
        }
        
        public void delete_all()
        {
            Dlubal.WS.RSection1.Model.delete_allRequest inValue = new Dlubal.WS.RSection1.Model.delete_allRequest();
            Dlubal.WS.RSection1.Model.delete_allResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).delete_all(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.delete_all_historyResponse Dlubal.WS.RSection1.Model.IRSectionModel.delete_all_history(Dlubal.WS.RSection1.Model.delete_all_historyRequest request)
        {
            return base.Channel.delete_all_history(request);
        }
        
        public void delete_all_history()
        {
            Dlubal.WS.RSection1.Model.delete_all_historyRequest inValue = new Dlubal.WS.RSection1.Model.delete_all_historyRequest();
            Dlubal.WS.RSection1.Model.delete_all_historyResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).delete_all_history(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.delete_all_resultsResponse Dlubal.WS.RSection1.Model.IRSectionModel.delete_all_results(Dlubal.WS.RSection1.Model.delete_all_resultsRequest request)
        {
            return base.Channel.delete_all_results(request);
        }
        
        public void delete_all_results(bool delete_mesh)
        {
            Dlubal.WS.RSection1.Model.delete_all_resultsRequest inValue = new Dlubal.WS.RSection1.Model.delete_all_resultsRequest();
            inValue.delete_mesh = delete_mesh;
            Dlubal.WS.RSection1.Model.delete_all_resultsResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).delete_all_results(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.delete_objectResponse Dlubal.WS.RSection1.Model.IRSectionModel.delete_object(Dlubal.WS.RSection1.Model.delete_objectRequest request)
        {
            return base.Channel.delete_object(request);
        }
        
        public void delete_object(Dlubal.WS.RSection1.Model.object_types type, int no, int parent_no)
        {
            Dlubal.WS.RSection1.Model.delete_objectRequest inValue = new Dlubal.WS.RSection1.Model.delete_objectRequest();
            inValue.type = type;
            inValue.no = no;
            inValue.parent_no = parent_no;
            Dlubal.WS.RSection1.Model.delete_objectResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).delete_object(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.export_details_of_design_to_csvResponse Dlubal.WS.RSection1.Model.IRSectionModel.export_details_of_design_to_csv(Dlubal.WS.RSection1.Model.export_details_of_design_to_csvRequest request)
        {
            return base.Channel.export_details_of_design_to_csv(request);
        }
        
        public void export_details_of_design_to_csv(string targetDirectoryPath)
        {
            Dlubal.WS.RSection1.Model.export_details_of_design_to_csvRequest inValue = new Dlubal.WS.RSection1.Model.export_details_of_design_to_csvRequest();
            inValue.targetDirectoryPath = targetDirectoryPath;
            Dlubal.WS.RSection1.Model.export_details_of_design_to_csvResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).export_details_of_design_to_csv(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.export_to_tablesResponse Dlubal.WS.RSection1.Model.IRSectionModel.export_to_tables(Dlubal.WS.RSection1.Model.export_to_tablesRequest request)
        {
            return base.Channel.export_to_tables(request);
        }
        
        public void export_to_tables(string export_path)
        {
            Dlubal.WS.RSection1.Model.export_to_tablesRequest inValue = new Dlubal.WS.RSection1.Model.export_to_tablesRequest();
            inValue.export_path = export_path;
            Dlubal.WS.RSection1.Model.export_to_tablesResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).export_to_tables(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.finish_modificationResponse Dlubal.WS.RSection1.Model.IRSectionModel.finish_modification(Dlubal.WS.RSection1.Model.finish_modificationRequest request)
        {
            return base.Channel.finish_modification(request);
        }
        
        public void finish_modification()
        {
            Dlubal.WS.RSection1.Model.finish_modificationRequest inValue = new Dlubal.WS.RSection1.Model.finish_modificationRequest();
            Dlubal.WS.RSection1.Model.finish_modificationResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).finish_modification(inValue);
        }
        
        public Dlubal.WS.RSection1.Model.generate_and_validate_xml_solver_input_result generate_and_validate_xml_solver_input(string solver_input_file_path)
        {
            Dlubal.WS.RSection1.Model.generate_and_validate_xml_solver_inputRequest inValue = new Dlubal.WS.RSection1.Model.generate_and_validate_xml_solver_inputRequest();
            inValue.solver_input_file_path = solver_input_file_path;
            Dlubal.WS.RSection1.Model.generate_and_validate_xml_solver_inputResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).generate_and_validate_xml_solver_input(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.generate_and_validate_xml_solver_inputResponse Dlubal.WS.RSection1.Model.IRSectionModel.generate_and_validate_xml_solver_input(Dlubal.WS.RSection1.Model.generate_and_validate_xml_solver_inputRequest request)
        {
            return base.Channel.generate_and_validate_xml_solver_input(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.generate_meshResponse Dlubal.WS.RSection1.Model.IRSectionModel.generate_mesh(Dlubal.WS.RSection1.Model.generate_meshRequest request)
        {
            return base.Channel.generate_mesh(request);
        }
        
        public Dlubal.WS.RSection1.Model.calculation_message[] generate_mesh(bool skip_warnings)
        {
            Dlubal.WS.RSection1.Model.generate_meshRequest inValue = new Dlubal.WS.RSection1.Model.generate_meshRequest();
            inValue.skip_warnings = skip_warnings;
            Dlubal.WS.RSection1.Model.generate_meshResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).generate_mesh(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_all_object_numbersResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_all_object_numbers(Dlubal.WS.RSection1.Model.get_all_object_numbersRequest request)
        {
            return base.Channel.get_all_object_numbers(request);
        }
        
        public int[] get_all_object_numbers(Dlubal.WS.RSection1.Model.object_types type, int parent_no)
        {
            Dlubal.WS.RSection1.Model.get_all_object_numbersRequest inValue = new Dlubal.WS.RSection1.Model.get_all_object_numbersRequest();
            inValue.type = type;
            inValue.parent_no = parent_no;
            Dlubal.WS.RSection1.Model.get_all_object_numbersResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_all_object_numbers(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_all_object_numbers_by_typeResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_all_object_numbers_by_type(Dlubal.WS.RSection1.Model.get_all_object_numbers_by_typeRequest request)
        {
            return base.Channel.get_all_object_numbers_by_type(request);
        }
        
        public Dlubal.WS.RSection1.Model.object_with_children[] get_all_object_numbers_by_type(Dlubal.WS.RSection1.Model.object_types type)
        {
            Dlubal.WS.RSection1.Model.get_all_object_numbers_by_typeRequest inValue = new Dlubal.WS.RSection1.Model.get_all_object_numbers_by_typeRequest();
            inValue.type = type;
            Dlubal.WS.RSection1.Model.get_all_object_numbers_by_typeResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_all_object_numbers_by_type(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_all_selected_objectsResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_all_selected_objects(Dlubal.WS.RSection1.Model.get_all_selected_objectsRequest request)
        {
            return base.Channel.get_all_selected_objects(request);
        }
        
        public Dlubal.WS.RSection1.Model.object_location[] get_all_selected_objects()
        {
            Dlubal.WS.RSection1.Model.get_all_selected_objectsRequest inValue = new Dlubal.WS.RSection1.Model.get_all_selected_objectsRequest();
            Dlubal.WS.RSection1.Model.get_all_selected_objectsResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_all_selected_objects(inValue);
            return retVal.value;
        }
        
        public Dlubal.WS.RSection1.Model.element get_element(int no)
        {
            Dlubal.WS.RSection1.Model.get_elementRequest inValue = new Dlubal.WS.RSection1.Model.get_elementRequest();
            inValue.no = no;
            Dlubal.WS.RSection1.Model.get_elementResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_element(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_elementResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_element(Dlubal.WS.RSection1.Model.get_elementRequest request)
        {
            return base.Channel.get_element(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_first_free_numberResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_first_free_number(Dlubal.WS.RSection1.Model.get_first_free_numberRequest request)
        {
            return base.Channel.get_first_free_number(request);
        }
        
        public int get_first_free_number(Dlubal.WS.RSection1.Model.object_types type, int parent_no)
        {
            Dlubal.WS.RSection1.Model.get_first_free_numberRequest inValue = new Dlubal.WS.RSection1.Model.get_first_free_numberRequest();
            inValue.type = type;
            inValue.parent_no = parent_no;
            Dlubal.WS.RSection1.Model.get_first_free_numberResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_first_free_number(inValue);
            return retVal.value;
        }
        
        public Dlubal.WS.RSection1.Model.formula_data get_formula(Dlubal.WS.RSection1.Model.object_location object_location, Dlubal.WS.RSection1.Model.object_parameter_location object_parameter_location)
        {
            Dlubal.WS.RSection1.Model.get_formulaRequest inValue = new Dlubal.WS.RSection1.Model.get_formulaRequest();
            inValue.object_location = object_location;
            inValue.object_parameter_location = object_parameter_location;
            Dlubal.WS.RSection1.Model.get_formulaResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_formula(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_formulaResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_formula(Dlubal.WS.RSection1.Model.get_formulaRequest request)
        {
            return base.Channel.get_formula(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_lineResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_line(Dlubal.WS.RSection1.Model.get_lineRequest request)
        {
            return base.Channel.get_line(request);
        }
        
        public Dlubal.WS.RSection1.Model.line get_line(int no)
        {
            Dlubal.WS.RSection1.Model.get_lineRequest inValue = new Dlubal.WS.RSection1.Model.get_lineRequest();
            inValue.no = no;
            Dlubal.WS.RSection1.Model.get_lineResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_line(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_list_of_parameters_formula_allowed_forResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_list_of_parameters_formula_allowed_for(Dlubal.WS.RSection1.Model.get_list_of_parameters_formula_allowed_forRequest request)
        {
            return base.Channel.get_list_of_parameters_formula_allowed_for(request);
        }
        
        public Dlubal.WS.RSection1.Model.object_parameter_location[] get_list_of_parameters_formula_allowed_for(Dlubal.WS.RSection1.Model.object_location object_location)
        {
            Dlubal.WS.RSection1.Model.get_list_of_parameters_formula_allowed_forRequest inValue = new Dlubal.WS.RSection1.Model.get_list_of_parameters_formula_allowed_forRequest();
            inValue.object_location = object_location;
            Dlubal.WS.RSection1.Model.get_list_of_parameters_formula_allowed_forResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_list_of_parameters_formula_allowed_for(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_load_cases_and_combinationsResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_load_cases_and_combinations(Dlubal.WS.RSection1.Model.get_load_cases_and_combinationsRequest request)
        {
            return base.Channel.get_load_cases_and_combinations(request);
        }
        
        public Dlubal.WS.RSection1.Model.load_cases_and_combinations get_load_cases_and_combinations()
        {
            Dlubal.WS.RSection1.Model.get_load_cases_and_combinationsRequest inValue = new Dlubal.WS.RSection1.Model.get_load_cases_and_combinationsRequest();
            Dlubal.WS.RSection1.Model.get_load_cases_and_combinationsResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_load_cases_and_combinations(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_materialResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_material(Dlubal.WS.RSection1.Model.get_materialRequest request)
        {
            return base.Channel.get_material(request);
        }
        
        public Dlubal.WS.RSection1.Model.material get_material(int no)
        {
            Dlubal.WS.RSection1.Model.get_materialRequest inValue = new Dlubal.WS.RSection1.Model.get_materialRequest();
            inValue.no = no;
            Dlubal.WS.RSection1.Model.get_materialResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_material(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_mesh_statisticsResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_mesh_statistics(Dlubal.WS.RSection1.Model.get_mesh_statisticsRequest request)
        {
            return base.Channel.get_mesh_statistics(request);
        }
        
        public Dlubal.WS.RSection1.Model.mesh_statistics_type get_mesh_statistics()
        {
            Dlubal.WS.RSection1.Model.get_mesh_statisticsRequest inValue = new Dlubal.WS.RSection1.Model.get_mesh_statisticsRequest();
            Dlubal.WS.RSection1.Model.get_mesh_statisticsResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_mesh_statistics(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_model_historyResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_model_history(Dlubal.WS.RSection1.Model.get_model_historyRequest request)
        {
            return base.Channel.get_model_history(request);
        }
        
        public Dlubal.WS.RSection1.Model.model_history_row[] get_model_history()
        {
            Dlubal.WS.RSection1.Model.get_model_historyRequest inValue = new Dlubal.WS.RSection1.Model.get_model_historyRequest();
            Dlubal.WS.RSection1.Model.get_model_historyResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_model_history(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_model_infoResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_model_info(Dlubal.WS.RSection1.Model.get_model_infoRequest request)
        {
            return base.Channel.get_model_info(request);
        }
        
        public Dlubal.WS.RSection1.Model.modelInfo get_model_info()
        {
            Dlubal.WS.RSection1.Model.get_model_infoRequest inValue = new Dlubal.WS.RSection1.Model.get_model_infoRequest();
            Dlubal.WS.RSection1.Model.get_model_infoResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_model_info(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_model_main_parametersResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_model_main_parameters(Dlubal.WS.RSection1.Model.get_model_main_parametersRequest request)
        {
            return base.Channel.get_model_main_parameters(request);
        }
        
        public Dlubal.WS.RSection1.Model.model_main_parameters get_model_main_parameters()
        {
            Dlubal.WS.RSection1.Model.get_model_main_parametersRequest inValue = new Dlubal.WS.RSection1.Model.get_model_main_parametersRequest();
            Dlubal.WS.RSection1.Model.get_model_main_parametersResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_model_main_parameters(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_model_parametersResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_model_parameters(Dlubal.WS.RSection1.Model.get_model_parametersRequest request)
        {
            return base.Channel.get_model_parameters(request);
        }
        
        public Dlubal.WS.RSection1.Model.model_parameters_row[] get_model_parameters()
        {
            Dlubal.WS.RSection1.Model.get_model_parametersRequest inValue = new Dlubal.WS.RSection1.Model.get_model_parametersRequest();
            Dlubal.WS.RSection1.Model.get_model_parametersResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_model_parameters(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_model_parameters_locationResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_model_parameters_location(Dlubal.WS.RSection1.Model.get_model_parameters_locationRequest request)
        {
            return base.Channel.get_model_parameters_location(request);
        }
        
        public Dlubal.WS.RSection1.Model.model_parameters_location_row[] get_model_parameters_location()
        {
            Dlubal.WS.RSection1.Model.get_model_parameters_locationRequest inValue = new Dlubal.WS.RSection1.Model.get_model_parameters_locationRequest();
            Dlubal.WS.RSection1.Model.get_model_parameters_locationResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_model_parameters_location(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_model_settings_and_optionsResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_model_settings_and_options(Dlubal.WS.RSection1.Model.get_model_settings_and_optionsRequest request)
        {
            return base.Channel.get_model_settings_and_options(request);
        }
        
        public Dlubal.WS.RSection1.Model.model_settings_and_options get_model_settings_and_options()
        {
            Dlubal.WS.RSection1.Model.get_model_settings_and_optionsRequest inValue = new Dlubal.WS.RSection1.Model.get_model_settings_and_optionsRequest();
            Dlubal.WS.RSection1.Model.get_model_settings_and_optionsResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_model_settings_and_options(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_nth_object_numberResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_nth_object_number(Dlubal.WS.RSection1.Model.get_nth_object_numberRequest request)
        {
            return base.Channel.get_nth_object_number(request);
        }
        
        public int get_nth_object_number(Dlubal.WS.RSection1.Model.object_types type, int order, int parent_no)
        {
            Dlubal.WS.RSection1.Model.get_nth_object_numberRequest inValue = new Dlubal.WS.RSection1.Model.get_nth_object_numberRequest();
            inValue.type = type;
            inValue.order = order;
            inValue.parent_no = parent_no;
            Dlubal.WS.RSection1.Model.get_nth_object_numberResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_nth_object_number(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_object_countResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_object_count(Dlubal.WS.RSection1.Model.get_object_countRequest request)
        {
            return base.Channel.get_object_count(request);
        }
        
        public int get_object_count(Dlubal.WS.RSection1.Model.object_types type, int parent_no)
        {
            Dlubal.WS.RSection1.Model.get_object_countRequest inValue = new Dlubal.WS.RSection1.Model.get_object_countRequest();
            inValue.type = type;
            inValue.parent_no = parent_no;
            Dlubal.WS.RSection1.Model.get_object_countResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_object_count(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_object_informationResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_object_information(Dlubal.WS.RSection1.Model.get_object_informationRequest request)
        {
            return base.Channel.get_object_information(request);
        }
        
        public Dlubal.WS.RSection1.Model.object_information get_object_information(Dlubal.WS.RSection1.Model.object_types type)
        {
            Dlubal.WS.RSection1.Model.get_object_informationRequest inValue = new Dlubal.WS.RSection1.Model.get_object_informationRequest();
            inValue.type = type;
            Dlubal.WS.RSection1.Model.get_object_informationResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_object_information(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_openingResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_opening(Dlubal.WS.RSection1.Model.get_openingRequest request)
        {
            return base.Channel.get_opening(request);
        }
        
        public Dlubal.WS.RSection1.Model.opening get_opening(int no)
        {
            Dlubal.WS.RSection1.Model.get_openingRequest inValue = new Dlubal.WS.RSection1.Model.get_openingRequest();
            inValue.no = no;
            Dlubal.WS.RSection1.Model.get_openingResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_opening(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_optimization_settingsResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_optimization_settings(Dlubal.WS.RSection1.Model.get_optimization_settingsRequest request)
        {
            return base.Channel.get_optimization_settings(request);
        }
        
        public Dlubal.WS.RSection1.Model.optimizationSettingsConfig get_optimization_settings()
        {
            Dlubal.WS.RSection1.Model.get_optimization_settingsRequest inValue = new Dlubal.WS.RSection1.Model.get_optimization_settingsRequest();
            Dlubal.WS.RSection1.Model.get_optimization_settingsResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_optimization_settings(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_partResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_part(Dlubal.WS.RSection1.Model.get_partRequest request)
        {
            return base.Channel.get_part(request);
        }
        
        public Dlubal.WS.RSection1.Model.part get_part(int no)
        {
            Dlubal.WS.RSection1.Model.get_partRequest inValue = new Dlubal.WS.RSection1.Model.get_partRequest();
            inValue.no = no;
            Dlubal.WS.RSection1.Model.get_partResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_part(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_pointResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_point(Dlubal.WS.RSection1.Model.get_pointRequest request)
        {
            return base.Channel.get_point(request);
        }
        
        public Dlubal.WS.RSection1.Model.point get_point(int no)
        {
            Dlubal.WS.RSection1.Model.get_pointRequest inValue = new Dlubal.WS.RSection1.Model.get_pointRequest();
            inValue.no = no;
            Dlubal.WS.RSection1.Model.get_pointResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_point(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_sectionResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_section(Dlubal.WS.RSection1.Model.get_sectionRequest request)
        {
            return base.Channel.get_section(request);
        }
        
        public Dlubal.WS.RSection1.Model.section get_section(int no)
        {
            Dlubal.WS.RSection1.Model.get_sectionRequest inValue = new Dlubal.WS.RSection1.Model.get_sectionRequest();
            inValue.no = no;
            Dlubal.WS.RSection1.Model.get_sectionResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_section(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_stress_pointResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_stress_point(Dlubal.WS.RSection1.Model.get_stress_pointRequest request)
        {
            return base.Channel.get_stress_point(request);
        }
        
        public Dlubal.WS.RSection1.Model.stress_point get_stress_point(int no)
        {
            Dlubal.WS.RSection1.Model.get_stress_pointRequest inValue = new Dlubal.WS.RSection1.Model.get_stress_pointRequest();
            inValue.no = no;
            Dlubal.WS.RSection1.Model.get_stress_pointResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_stress_point(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_subpanelResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_subpanel(Dlubal.WS.RSection1.Model.get_subpanelRequest request)
        {
            return base.Channel.get_subpanel(request);
        }
        
        public Dlubal.WS.RSection1.Model.subpanel get_subpanel(int no)
        {
            Dlubal.WS.RSection1.Model.get_subpanelRequest inValue = new Dlubal.WS.RSection1.Model.get_subpanelRequest();
            inValue.no = no;
            Dlubal.WS.RSection1.Model.get_subpanelResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_subpanel(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.get_table_export_config_managerResponse Dlubal.WS.RSection1.Model.IRSectionModel.get_table_export_config_manager(Dlubal.WS.RSection1.Model.get_table_export_config_managerRequest request)
        {
            return base.Channel.get_table_export_config_manager(request);
        }
        
        public Dlubal.WS.RSection1.Model.TableExportConfigManager get_table_export_config_manager()
        {
            Dlubal.WS.RSection1.Model.get_table_export_config_managerRequest inValue = new Dlubal.WS.RSection1.Model.get_table_export_config_managerRequest();
            Dlubal.WS.RSection1.Model.get_table_export_config_managerResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).get_table_export_config_manager(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.resetResponse Dlubal.WS.RSection1.Model.IRSectionModel.reset(Dlubal.WS.RSection1.Model.resetRequest request)
        {
            return base.Channel.reset(request);
        }
        
        public void reset()
        {
            Dlubal.WS.RSection1.Model.resetRequest inValue = new Dlubal.WS.RSection1.Model.resetRequest();
            Dlubal.WS.RSection1.Model.resetResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).reset(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.run_scriptResponse Dlubal.WS.RSection1.Model.IRSectionModel.run_script(Dlubal.WS.RSection1.Model.run_scriptRequest request)
        {
            return base.Channel.run_script(request);
        }
        
        public void run_script(string script_file_path)
        {
            Dlubal.WS.RSection1.Model.run_scriptRequest inValue = new Dlubal.WS.RSection1.Model.run_scriptRequest();
            inValue.script_file_path = script_file_path;
            Dlubal.WS.RSection1.Model.run_scriptResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).run_script(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.saveResponse Dlubal.WS.RSection1.Model.IRSectionModel.save(Dlubal.WS.RSection1.Model.saveRequest request)
        {
            return base.Channel.save(request);
        }
        
        public bool save(string file_path)
        {
            Dlubal.WS.RSection1.Model.saveRequest inValue = new Dlubal.WS.RSection1.Model.saveRequest();
            inValue.file_path = file_path;
            Dlubal.WS.RSection1.Model.saveResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).save(inValue);
            return retVal.value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_elementResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_element(Dlubal.WS.RSection1.Model.set_elementRequest request)
        {
            return base.Channel.set_element(request);
        }
        
        public void set_element(Dlubal.WS.RSection1.Model.element value)
        {
            Dlubal.WS.RSection1.Model.set_elementRequest inValue = new Dlubal.WS.RSection1.Model.set_elementRequest();
            inValue.value = value;
            Dlubal.WS.RSection1.Model.set_elementResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_element(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_formulaResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_formula(Dlubal.WS.RSection1.Model.set_formulaRequest request)
        {
            return base.Channel.set_formula(request);
        }
        
        public void set_formula(Dlubal.WS.RSection1.Model.object_location object_location, Dlubal.WS.RSection1.Model.object_parameter_location object_parameter_location, string formula)
        {
            Dlubal.WS.RSection1.Model.set_formulaRequest inValue = new Dlubal.WS.RSection1.Model.set_formulaRequest();
            inValue.object_location = object_location;
            inValue.object_parameter_location = object_parameter_location;
            inValue.formula = formula;
            Dlubal.WS.RSection1.Model.set_formulaResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_formula(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_lineResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_line(Dlubal.WS.RSection1.Model.set_lineRequest request)
        {
            return base.Channel.set_line(request);
        }
        
        public void set_line(Dlubal.WS.RSection1.Model.line value)
        {
            Dlubal.WS.RSection1.Model.set_lineRequest inValue = new Dlubal.WS.RSection1.Model.set_lineRequest();
            inValue.value = value;
            Dlubal.WS.RSection1.Model.set_lineResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_line(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_load_cases_and_combinationsResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_load_cases_and_combinations(Dlubal.WS.RSection1.Model.set_load_cases_and_combinationsRequest request)
        {
            return base.Channel.set_load_cases_and_combinations(request);
        }
        
        public void set_load_cases_and_combinations(Dlubal.WS.RSection1.Model.load_cases_and_combinations value)
        {
            Dlubal.WS.RSection1.Model.set_load_cases_and_combinationsRequest inValue = new Dlubal.WS.RSection1.Model.set_load_cases_and_combinationsRequest();
            inValue.value = value;
            Dlubal.WS.RSection1.Model.set_load_cases_and_combinationsResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_load_cases_and_combinations(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_materialResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_material(Dlubal.WS.RSection1.Model.set_materialRequest request)
        {
            return base.Channel.set_material(request);
        }
        
        public void set_material(Dlubal.WS.RSection1.Model.material value)
        {
            Dlubal.WS.RSection1.Model.set_materialRequest inValue = new Dlubal.WS.RSection1.Model.set_materialRequest();
            inValue.value = value;
            Dlubal.WS.RSection1.Model.set_materialResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_material(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_model_historyResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_model_history(Dlubal.WS.RSection1.Model.set_model_historyRequest request)
        {
            return base.Channel.set_model_history(request);
        }
        
        public void set_model_history(Dlubal.WS.RSection1.Model.model_history_row[] table_values)
        {
            Dlubal.WS.RSection1.Model.set_model_historyRequest inValue = new Dlubal.WS.RSection1.Model.set_model_historyRequest();
            inValue.table_values = table_values;
            Dlubal.WS.RSection1.Model.set_model_historyResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_model_history(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_model_parametersResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_model_parameters(Dlubal.WS.RSection1.Model.set_model_parametersRequest request)
        {
            return base.Channel.set_model_parameters(request);
        }
        
        public void set_model_parameters(Dlubal.WS.RSection1.Model.model_parameters_row[] table_values)
        {
            Dlubal.WS.RSection1.Model.set_model_parametersRequest inValue = new Dlubal.WS.RSection1.Model.set_model_parametersRequest();
            inValue.table_values = table_values;
            Dlubal.WS.RSection1.Model.set_model_parametersResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_model_parameters(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_model_parameters_locationResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_model_parameters_location(Dlubal.WS.RSection1.Model.set_model_parameters_locationRequest request)
        {
            return base.Channel.set_model_parameters_location(request);
        }
        
        public void set_model_parameters_location(Dlubal.WS.RSection1.Model.model_parameters_location_row[] table_values)
        {
            Dlubal.WS.RSection1.Model.set_model_parameters_locationRequest inValue = new Dlubal.WS.RSection1.Model.set_model_parameters_locationRequest();
            inValue.table_values = table_values;
            Dlubal.WS.RSection1.Model.set_model_parameters_locationResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_model_parameters_location(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_model_settings_and_optionsResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_model_settings_and_options(Dlubal.WS.RSection1.Model.set_model_settings_and_optionsRequest request)
        {
            return base.Channel.set_model_settings_and_options(request);
        }
        
        public void set_model_settings_and_options(Dlubal.WS.RSection1.Model.model_settings_and_options model_settings_and_options)
        {
            Dlubal.WS.RSection1.Model.set_model_settings_and_optionsRequest inValue = new Dlubal.WS.RSection1.Model.set_model_settings_and_optionsRequest();
            inValue.model_settings_and_options = model_settings_and_options;
            Dlubal.WS.RSection1.Model.set_model_settings_and_optionsResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_model_settings_and_options(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_openingResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_opening(Dlubal.WS.RSection1.Model.set_openingRequest request)
        {
            return base.Channel.set_opening(request);
        }
        
        public void set_opening(Dlubal.WS.RSection1.Model.opening value)
        {
            Dlubal.WS.RSection1.Model.set_openingRequest inValue = new Dlubal.WS.RSection1.Model.set_openingRequest();
            inValue.value = value;
            Dlubal.WS.RSection1.Model.set_openingResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_opening(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_optimization_settingsResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_optimization_settings(Dlubal.WS.RSection1.Model.set_optimization_settingsRequest request)
        {
            return base.Channel.set_optimization_settings(request);
        }
        
        public void set_optimization_settings(Dlubal.WS.RSection1.Model.optimizationSettingsConfig value)
        {
            Dlubal.WS.RSection1.Model.set_optimization_settingsRequest inValue = new Dlubal.WS.RSection1.Model.set_optimization_settingsRequest();
            inValue.value = value;
            Dlubal.WS.RSection1.Model.set_optimization_settingsResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_optimization_settings(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_partResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_part(Dlubal.WS.RSection1.Model.set_partRequest request)
        {
            return base.Channel.set_part(request);
        }
        
        public void set_part(Dlubal.WS.RSection1.Model.part value)
        {
            Dlubal.WS.RSection1.Model.set_partRequest inValue = new Dlubal.WS.RSection1.Model.set_partRequest();
            inValue.value = value;
            Dlubal.WS.RSection1.Model.set_partResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_part(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_pointResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_point(Dlubal.WS.RSection1.Model.set_pointRequest request)
        {
            return base.Channel.set_point(request);
        }
        
        public void set_point(Dlubal.WS.RSection1.Model.point value)
        {
            Dlubal.WS.RSection1.Model.set_pointRequest inValue = new Dlubal.WS.RSection1.Model.set_pointRequest();
            inValue.value = value;
            Dlubal.WS.RSection1.Model.set_pointResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_point(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_sectionResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_section(Dlubal.WS.RSection1.Model.set_sectionRequest request)
        {
            return base.Channel.set_section(request);
        }
        
        public void set_section(Dlubal.WS.RSection1.Model.section value)
        {
            Dlubal.WS.RSection1.Model.set_sectionRequest inValue = new Dlubal.WS.RSection1.Model.set_sectionRequest();
            inValue.value = value;
            Dlubal.WS.RSection1.Model.set_sectionResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_section(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_selected_objectsResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_selected_objects(Dlubal.WS.RSection1.Model.set_selected_objectsRequest request)
        {
            return base.Channel.set_selected_objects(request);
        }
        
        public void set_selected_objects(Dlubal.WS.RSection1.Model.object_location[] object_locations)
        {
            Dlubal.WS.RSection1.Model.set_selected_objectsRequest inValue = new Dlubal.WS.RSection1.Model.set_selected_objectsRequest();
            inValue.object_locations = object_locations;
            Dlubal.WS.RSection1.Model.set_selected_objectsResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_selected_objects(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_stress_pointResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_stress_point(Dlubal.WS.RSection1.Model.set_stress_pointRequest request)
        {
            return base.Channel.set_stress_point(request);
        }
        
        public void set_stress_point(Dlubal.WS.RSection1.Model.stress_point value)
        {
            Dlubal.WS.RSection1.Model.set_stress_pointRequest inValue = new Dlubal.WS.RSection1.Model.set_stress_pointRequest();
            inValue.value = value;
            Dlubal.WS.RSection1.Model.set_stress_pointResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_stress_point(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_subpanelResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_subpanel(Dlubal.WS.RSection1.Model.set_subpanelRequest request)
        {
            return base.Channel.set_subpanel(request);
        }
        
        public void set_subpanel(Dlubal.WS.RSection1.Model.subpanel value)
        {
            Dlubal.WS.RSection1.Model.set_subpanelRequest inValue = new Dlubal.WS.RSection1.Model.set_subpanelRequest();
            inValue.value = value;
            Dlubal.WS.RSection1.Model.set_subpanelResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_subpanel(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dlubal.WS.RSection1.Model.set_table_export_config_managerResponse Dlubal.WS.RSection1.Model.IRSectionModel.set_table_export_config_manager(Dlubal.WS.RSection1.Model.set_table_export_config_managerRequest request)
        {
            return base.Channel.set_table_export_config_manager(request);
        }
        
        public void set_table_export_config_manager(Dlubal.WS.RSection1.Model.TableExportConfigManager value)
        {
            Dlubal.WS.RSection1.Model.set_table_export_config_managerRequest inValue = new Dlubal.WS.RSection1.Model.set_table_export_config_managerRequest();
            inValue.value = value;
            Dlubal.WS.RSection1.Model.set_table_export_config_managerResponse retVal = ((Dlubal.WS.RSection1.Model.IRSectionModel)(this)).set_table_export_config_manager(inValue);
        }
    }
}
