//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dlubal.WS.RSection1.Application
{
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dlubal.com/rsection.xsd")]
    public enum application_types
    {
        
        /// <remarks/>
        CRASH_REPORTER,
        
        /// <remarks/>
        DLUBAL_CENTER,
        
        /// <remarks/>
        REPORT_VIEWER,
        
        /// <remarks/>
        RFEM6,
        
        /// <remarks/>
        RSECTION,
        
        /// <remarks/>
        RSTAB9,
        
        /// <remarks/>
        WEB_SECTIONS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dlubal.com/rsection.xsd")]
    public enum program_language_name_type
    {
        
        /// <remarks/>
        CHINESE,
        
        /// <remarks/>
        CZECH,
        
        /// <remarks/>
        DUTCH,
        
        /// <remarks/>
        ENGLISH,
        
        /// <remarks/>
        FRENCH,
        
        /// <remarks/>
        GERMAN,
        
        /// <remarks/>
        GREEK,
        
        /// <remarks/>
        ITALIAN,
        
        /// <remarks/>
        POLISH,
        
        /// <remarks/>
        PORTUGUESE,
        
        /// <remarks/>
        RUSSIAN,
        
        /// <remarks/>
        SPANISH,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dlubal.com/rsection.xsd")]
    public enum region_type
    {
        
        /// <remarks/>
        DEFAULT,
        
        /// <remarks/>
        EASTERN_EUROPE,
        
        /// <remarks/>
        EAST_ASIA,
        
        /// <remarks/>
        NORTH_AMERICA_CANADA,
        
        /// <remarks/>
        NORTH_AMERICA_USA,
        
        /// <remarks/>
        SOUTHEAST_ASIA,
        
        /// <remarks/>
        WESTERN_EUROPE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dlubal.com/rsection.xsd")]
    public enum unit_system_type
    {
        
        /// <remarks/>
        IMPERIAL,
        
        /// <remarks/>
        METRIC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dlubal.com/rsection.xsd")]
    public partial class application_information : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string nameField;
        
        private application_types typeField;
        
        private bool server_instanceField;
        
        private string versionField;
        
        private string full_versionField;
        
        private string optionsField;
        
        private string language_nameField;
        
        private string language_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public application_types type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool server_instance
        {
            get
            {
                return this.server_instanceField;
            }
            set
            {
                this.server_instanceField = value;
                this.RaisePropertyChanged("server_instance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string full_version
        {
            get
            {
                return this.full_versionField;
            }
            set
            {
                this.full_versionField = value;
                this.RaisePropertyChanged("full_version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string options
        {
            get
            {
                return this.optionsField;
            }
            set
            {
                this.optionsField = value;
                this.RaisePropertyChanged("options");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string language_name
        {
            get
            {
                return this.language_nameField;
            }
            set
            {
                this.language_nameField = value;
                this.RaisePropertyChanged("language_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string language_id
        {
            get
            {
                return this.language_idField;
            }
            set
            {
                this.language_idField = value;
                this.RaisePropertyChanged("language_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="close_application", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class close_applicationRequest
    {
        
        public close_applicationRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="close_applicationResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class close_applicationResponse
    {
        
        public close_applicationResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="close_model", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class close_modelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int index;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool save_changes;
        
        public close_modelRequest()
        {
        }
        
        public close_modelRequest(int index, bool save_changes)
        {
            this.index = index;
            this.save_changes = save_changes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="close_modelResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class close_modelResponse
    {
        
        public close_modelResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete_project", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class delete_projectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string project_path;
        
        public delete_projectRequest()
        {
        }
        
        public delete_projectRequest(string project_path)
        {
            this.project_path = project_path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete_projectResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class delete_projectResponse
    {
        
        public delete_projectResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_active_model", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_active_modelRequest
    {
        
        public get_active_modelRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_active_modelResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_active_modelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value;
        
        public get_active_modelResponse()
        {
        }
        
        public get_active_modelResponse(string value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_current_project", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_current_projectRequest
    {
        
        public get_current_projectRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_current_projectResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_current_projectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dlubal.WS.RSection1.Application.project_info value;
        
        public get_current_projectResponse()
        {
        }
        
        public get_current_projectResponse(Dlubal.WS.RSection1.Application.project_info value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_detailed_logging", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_detailed_loggingRequest
    {
        
        public get_detailed_loggingRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_detailed_loggingResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_detailed_loggingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool value;
        
        public get_detailed_loggingResponse()
        {
        }
        
        public get_detailed_loggingResponse(bool value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_information", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_informationRequest
    {
        
        public get_informationRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_informationResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_informationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dlubal.WS.RSection1.Application.application_information value;
        
        public get_informationResponse()
        {
        }
        
        public get_informationResponse(Dlubal.WS.RSection1.Application.application_information value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_list_of_existing_projects", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_list_of_existing_projectsRequest
    {
        
        public get_list_of_existing_projectsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_list_of_existing_projectsResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_list_of_existing_projectsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Dlubal.WS.RSection1.Application.project_info[] value;
        
        public get_list_of_existing_projectsResponse()
        {
        }
        
        public get_list_of_existing_projectsResponse(Dlubal.WS.RSection1.Application.project_info[] value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_model_list_with_indexes", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_model_list_with_indexesRequest
    {
        
        public get_model_list_with_indexesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_model_list_with_indexesResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_model_list_with_indexesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Dlubal.WS.RSection1.Application.model_name_and_index[] value;
        
        public get_model_list_with_indexesResponse()
        {
        }
        
        public get_model_list_with_indexesResponse(Dlubal.WS.RSection1.Application.model_name_and_index[] value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_model_list", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_model_listRequest
    {
        
        public get_model_listRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_model_listResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_model_listResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] value;
        
        public get_model_listResponse()
        {
        }
        
        public get_model_listResponse(string[] value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_model", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_modelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int index;
        
        public get_modelRequest()
        {
        }
        
        public get_modelRequest(int index)
        {
            this.index = index;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_modelResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_modelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value;
        
        public get_modelResponse()
        {
        }
        
        public get_modelResponse(string value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_program_options", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_program_optionsRequest
    {
        
        public get_program_optionsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_program_optionsResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_program_optionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dlubal.WS.RSection1.Application.settings_program_options value;
        
        public get_program_optionsResponse()
        {
        }
        
        public get_program_optionsResponse(Dlubal.WS.RSection1.Application.settings_program_options value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_program_settings", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_program_settingsRequest
    {
        
        public get_program_settingsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_program_settingsResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_program_settingsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dlubal.WS.RSection1.Application.program_settings value;
        
        public get_program_settingsResponse()
        {
        }
        
        public get_program_settingsResponse(Dlubal.WS.RSection1.Application.program_settings value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_project", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_projectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string project_path;
        
        public get_projectRequest()
        {
        }
        
        public get_projectRequest(string project_path)
        {
            this.project_path = project_path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_projectResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_projectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dlubal.WS.RSection1.Application.project_info value;
        
        public get_projectResponse()
        {
        }
        
        public get_projectResponse(Dlubal.WS.RSection1.Application.project_info value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_session_id", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_session_idRequest
    {
        
        public get_session_idRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_session_idResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_session_idResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value;
        
        public get_session_idResponse()
        {
        }
        
        public get_session_idResponse(string value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_settings_program_language", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_settings_program_languageRequest
    {
        
        public get_settings_program_languageRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_settings_program_languageResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class get_settings_program_languageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dlubal.WS.RSection1.Application.settings_program_language value;
        
        public get_settings_program_languageResponse()
        {
        }
        
        public get_settings_program_languageResponse(Dlubal.WS.RSection1.Application.settings_program_language value)
        {
            this.value = value;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dlubal.com/rsection.xsd")]
    public partial class import_from_output : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string end_pointField;
        
        private string reportField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string end_point
        {
            get
            {
                return this.end_pointField;
            }
            set
            {
                this.end_pointField = value;
                this.RaisePropertyChanged("end_point");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string report
        {
            get
            {
                return this.reportField;
            }
            set
            {
                this.reportField = value;
                this.RaisePropertyChanged("report");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="import_from", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class import_fromRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string file_path;
        
        public import_fromRequest()
        {
        }
        
        public import_fromRequest(string file_path)
        {
            this.file_path = file_path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="import_fromResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class import_fromResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dlubal.WS.RSection1.Application.import_from_output value;
        
        public import_fromResponse()
        {
        }
        
        public import_fromResponse(Dlubal.WS.RSection1.Application.import_from_output value)
        {
            this.value = value;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dlubal.com/rsection.xsd")]
    public partial class model_name_and_index : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int indexField;
        
        private bool indexFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
                this.RaisePropertyChanged("index");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indexSpecified
        {
            get
            {
                return this.indexFieldSpecified;
            }
            set
            {
                this.indexFieldSpecified = value;
                this.RaisePropertyChanged("indexSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="new_model_as_copy", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class new_model_as_copyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string model_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string file_path;
        
        public new_model_as_copyRequest()
        {
        }
        
        public new_model_as_copyRequest(string model_name, string file_path)
        {
            this.model_name = model_name;
            this.file_path = file_path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="new_model_as_copyResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class new_model_as_copyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value;
        
        public new_model_as_copyResponse()
        {
        }
        
        public new_model_as_copyResponse(string value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="new_model_from_template", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class new_model_from_templateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string model_name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string file_path;
        
        public new_model_from_templateRequest()
        {
        }
        
        public new_model_from_templateRequest(string model_name, string file_path)
        {
            this.model_name = model_name;
            this.file_path = file_path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="new_model_from_templateResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class new_model_from_templateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value;
        
        public new_model_from_templateResponse()
        {
        }
        
        public new_model_from_templateResponse(string value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="new_model", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class new_modelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string model_name;
        
        public new_modelRequest()
        {
        }
        
        public new_modelRequest(string model_name)
        {
            this.model_name = model_name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="new_modelResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class new_modelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value;
        
        public new_modelResponse()
        {
        }
        
        public new_modelResponse(string value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="new_project", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class new_projectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dlubal.WS.RSection1.Application.project_info project_info;
        
        public new_projectRequest()
        {
        }
        
        public new_projectRequest(Dlubal.WS.RSection1.Application.project_info project_info)
        {
            this.project_info = project_info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="new_projectResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class new_projectResponse
    {
        
        public new_projectResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="open_model", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class open_modelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string model_path;
        
        public open_modelRequest()
        {
        }
        
        public open_modelRequest(string model_path)
        {
            this.model_path = model_path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="open_modelResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class open_modelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value;
        
        public open_modelResponse()
        {
        }
        
        public open_modelResponse(string value)
        {
            this.value = value;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dlubal.com/rsection.xsd")]
    public partial class program_settings : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int max_number_of_recent_filesField;
        
        private bool max_number_of_recent_filesFieldSpecified;
        
        private int max_number_of_recent_templatesField;
        
        private bool max_number_of_recent_templatesFieldSpecified;
        
        private int max_number_of_undo_stepsField;
        
        private bool max_number_of_undo_stepsFieldSpecified;
        
        private double formula_evaluation_time_limitField;
        
        private bool formula_evaluation_time_limitFieldSpecified;
        
        private string date_formatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int max_number_of_recent_files
        {
            get
            {
                return this.max_number_of_recent_filesField;
            }
            set
            {
                this.max_number_of_recent_filesField = value;
                this.RaisePropertyChanged("max_number_of_recent_files");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool max_number_of_recent_filesSpecified
        {
            get
            {
                return this.max_number_of_recent_filesFieldSpecified;
            }
            set
            {
                this.max_number_of_recent_filesFieldSpecified = value;
                this.RaisePropertyChanged("max_number_of_recent_filesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int max_number_of_recent_templates
        {
            get
            {
                return this.max_number_of_recent_templatesField;
            }
            set
            {
                this.max_number_of_recent_templatesField = value;
                this.RaisePropertyChanged("max_number_of_recent_templates");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool max_number_of_recent_templatesSpecified
        {
            get
            {
                return this.max_number_of_recent_templatesFieldSpecified;
            }
            set
            {
                this.max_number_of_recent_templatesFieldSpecified = value;
                this.RaisePropertyChanged("max_number_of_recent_templatesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int max_number_of_undo_steps
        {
            get
            {
                return this.max_number_of_undo_stepsField;
            }
            set
            {
                this.max_number_of_undo_stepsField = value;
                this.RaisePropertyChanged("max_number_of_undo_steps");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool max_number_of_undo_stepsSpecified
        {
            get
            {
                return this.max_number_of_undo_stepsFieldSpecified;
            }
            set
            {
                this.max_number_of_undo_stepsFieldSpecified = value;
                this.RaisePropertyChanged("max_number_of_undo_stepsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double formula_evaluation_time_limit
        {
            get
            {
                return this.formula_evaluation_time_limitField;
            }
            set
            {
                this.formula_evaluation_time_limitField = value;
                this.RaisePropertyChanged("formula_evaluation_time_limit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool formula_evaluation_time_limitSpecified
        {
            get
            {
                return this.formula_evaluation_time_limitFieldSpecified;
            }
            set
            {
                this.formula_evaluation_time_limitFieldSpecified = value;
                this.RaisePropertyChanged("formula_evaluation_time_limitSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string date_format
        {
            get
            {
                return this.date_formatField;
            }
            set
            {
                this.date_formatField = value;
                this.RaisePropertyChanged("date_format");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dlubal.com/rsection.xsd")]
    public partial class project_info : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string nameField;
        
        private string descriptionField;
        
        private string parent_pathField;
        
        private string folder_pathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string parent_path
        {
            get
            {
                return this.parent_pathField;
            }
            set
            {
                this.parent_pathField = value;
                this.RaisePropertyChanged("parent_path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string folder_path
        {
            get
            {
                return this.folder_pathField;
            }
            set
            {
                this.folder_pathField = value;
                this.RaisePropertyChanged("folder_path");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save_model", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class save_modelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int index;
        
        public save_modelRequest()
        {
        }
        
        public save_modelRequest(int index)
        {
            this.index = index;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save_modelResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class save_modelResponse
    {
        
        public save_modelResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="set_as_current_project", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class set_as_current_projectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string project_path;
        
        public set_as_current_projectRequest()
        {
        }
        
        public set_as_current_projectRequest(string project_path)
        {
            this.project_path = project_path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="set_as_current_projectResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class set_as_current_projectResponse
    {
        
        public set_as_current_projectResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="set_detailed_logging", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class set_detailed_loggingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool value;
        
        public set_detailed_loggingRequest()
        {
        }
        
        public set_detailed_loggingRequest(bool value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="set_detailed_loggingResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class set_detailed_loggingResponse
    {
        
        public set_detailed_loggingResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="set_program_options", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class set_program_optionsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dlubal.WS.RSection1.Application.settings_program_options program_options;
        
        public set_program_optionsRequest()
        {
        }
        
        public set_program_optionsRequest(Dlubal.WS.RSection1.Application.settings_program_options program_options)
        {
            this.program_options = program_options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="set_program_optionsResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class set_program_optionsResponse
    {
        
        public set_program_optionsResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="set_program_settings", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class set_program_settingsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dlubal.WS.RSection1.Application.program_settings program_settings;
        
        public set_program_settingsRequest()
        {
        }
        
        public set_program_settingsRequest(Dlubal.WS.RSection1.Application.program_settings program_settings)
        {
            this.program_settings = program_settings;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="set_program_settingsResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class set_program_settingsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value;
        
        public set_program_settingsResponse()
        {
        }
        
        public set_program_settingsResponse(string value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="set_settings_program_language", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class set_settings_program_languageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Dlubal.WS.RSection1.Application.settings_program_language settings_program_language;
        
        public set_settings_program_languageRequest()
        {
        }
        
        public set_settings_program_languageRequest(Dlubal.WS.RSection1.Application.settings_program_language settings_program_language)
        {
            this.settings_program_language = settings_program_language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="set_settings_program_languageResponse", WrapperNamespace="http://www.dlubal.com/rsection.xsd", IsWrapped=true)]
    public partial class set_settings_program_languageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.dlubal.com/rsection.xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value;
        
        public set_settings_program_languageResponse()
        {
        }
        
        public set_settings_program_languageResponse(string value)
        {
            this.value = value;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dlubal.com/rsection.xsd")]
    public partial class settings_program_language : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private program_language_name_type program_languageField;
        
        private bool program_languageFieldSpecified;
        
        private region_type regionField;
        
        private bool regionFieldSpecified;
        
        private unit_system_type unit_systemField;
        
        private bool unit_systemFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public program_language_name_type program_language
        {
            get
            {
                return this.program_languageField;
            }
            set
            {
                this.program_languageField = value;
                this.RaisePropertyChanged("program_language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool program_languageSpecified
        {
            get
            {
                return this.program_languageFieldSpecified;
            }
            set
            {
                this.program_languageFieldSpecified = value;
                this.RaisePropertyChanged("program_languageSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public region_type region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool regionSpecified
        {
            get
            {
                return this.regionFieldSpecified;
            }
            set
            {
                this.regionFieldSpecified = value;
                this.RaisePropertyChanged("regionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public unit_system_type unit_system
        {
            get
            {
                return this.unit_systemField;
            }
            set
            {
                this.unit_systemField = value;
                this.RaisePropertyChanged("unit_system");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unit_systemSpecified
        {
            get
            {
                return this.unit_systemFieldSpecified;
            }
            set
            {
                this.unit_systemFieldSpecified = value;
                this.RaisePropertyChanged("unit_systemSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.dlubal.com/rsection.xsd")]
    public partial class settings_program_options : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool multisamplingField;
        
        private bool multisamplingFieldSpecified;
        
        private bool animate_view_changesField;
        
        private bool animate_view_changesFieldSpecified;
        
        private bool auto_connect_lines_and_elementsField;
        
        private bool auto_connect_lines_and_elementsFieldSpecified;
        
        private bool by_internal_points_on_lineField;
        
        private bool by_internal_points_on_lineFieldSpecified;
        
        private bool load_last_opened_models_when_program_restartsField;
        
        private bool load_last_opened_models_when_program_restartsFieldSpecified;
        
        private bool delete_useless_points_during_importField;
        
        private bool delete_useless_points_during_importFieldSpecified;
        
        private bool load_last_saved_basic_objects_in_a_new_modelField;
        
        private bool load_last_saved_basic_objects_in_a_new_modelFieldSpecified;
        
        private bool validate_objects_when_selecting_in_graphicsField;
        
        private bool validate_objects_when_selecting_in_graphicsFieldSpecified;
        
        private bool automatic_save_to_backup_copyField;
        
        private bool automatic_save_to_backup_copyFieldSpecified;
        
        private bool save_after_calculationField;
        
        private bool save_after_calculationFieldSpecified;
        
        private int automatically_save_afterField;
        
        private bool automatically_save_afterFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool multisampling
        {
            get
            {
                return this.multisamplingField;
            }
            set
            {
                this.multisamplingField = value;
                this.RaisePropertyChanged("multisampling");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool multisamplingSpecified
        {
            get
            {
                return this.multisamplingFieldSpecified;
            }
            set
            {
                this.multisamplingFieldSpecified = value;
                this.RaisePropertyChanged("multisamplingSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool animate_view_changes
        {
            get
            {
                return this.animate_view_changesField;
            }
            set
            {
                this.animate_view_changesField = value;
                this.RaisePropertyChanged("animate_view_changes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool animate_view_changesSpecified
        {
            get
            {
                return this.animate_view_changesFieldSpecified;
            }
            set
            {
                this.animate_view_changesFieldSpecified = value;
                this.RaisePropertyChanged("animate_view_changesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool auto_connect_lines_and_elements
        {
            get
            {
                return this.auto_connect_lines_and_elementsField;
            }
            set
            {
                this.auto_connect_lines_and_elementsField = value;
                this.RaisePropertyChanged("auto_connect_lines_and_elements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool auto_connect_lines_and_elementsSpecified
        {
            get
            {
                return this.auto_connect_lines_and_elementsFieldSpecified;
            }
            set
            {
                this.auto_connect_lines_and_elementsFieldSpecified = value;
                this.RaisePropertyChanged("auto_connect_lines_and_elementsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool by_internal_points_on_line
        {
            get
            {
                return this.by_internal_points_on_lineField;
            }
            set
            {
                this.by_internal_points_on_lineField = value;
                this.RaisePropertyChanged("by_internal_points_on_line");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool by_internal_points_on_lineSpecified
        {
            get
            {
                return this.by_internal_points_on_lineFieldSpecified;
            }
            set
            {
                this.by_internal_points_on_lineFieldSpecified = value;
                this.RaisePropertyChanged("by_internal_points_on_lineSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool load_last_opened_models_when_program_restarts
        {
            get
            {
                return this.load_last_opened_models_when_program_restartsField;
            }
            set
            {
                this.load_last_opened_models_when_program_restartsField = value;
                this.RaisePropertyChanged("load_last_opened_models_when_program_restarts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool load_last_opened_models_when_program_restartsSpecified
        {
            get
            {
                return this.load_last_opened_models_when_program_restartsFieldSpecified;
            }
            set
            {
                this.load_last_opened_models_when_program_restartsFieldSpecified = value;
                this.RaisePropertyChanged("load_last_opened_models_when_program_restartsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool delete_useless_points_during_import
        {
            get
            {
                return this.delete_useless_points_during_importField;
            }
            set
            {
                this.delete_useless_points_during_importField = value;
                this.RaisePropertyChanged("delete_useless_points_during_import");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool delete_useless_points_during_importSpecified
        {
            get
            {
                return this.delete_useless_points_during_importFieldSpecified;
            }
            set
            {
                this.delete_useless_points_during_importFieldSpecified = value;
                this.RaisePropertyChanged("delete_useless_points_during_importSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool load_last_saved_basic_objects_in_a_new_model
        {
            get
            {
                return this.load_last_saved_basic_objects_in_a_new_modelField;
            }
            set
            {
                this.load_last_saved_basic_objects_in_a_new_modelField = value;
                this.RaisePropertyChanged("load_last_saved_basic_objects_in_a_new_model");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool load_last_saved_basic_objects_in_a_new_modelSpecified
        {
            get
            {
                return this.load_last_saved_basic_objects_in_a_new_modelFieldSpecified;
            }
            set
            {
                this.load_last_saved_basic_objects_in_a_new_modelFieldSpecified = value;
                this.RaisePropertyChanged("load_last_saved_basic_objects_in_a_new_modelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool validate_objects_when_selecting_in_graphics
        {
            get
            {
                return this.validate_objects_when_selecting_in_graphicsField;
            }
            set
            {
                this.validate_objects_when_selecting_in_graphicsField = value;
                this.RaisePropertyChanged("validate_objects_when_selecting_in_graphics");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validate_objects_when_selecting_in_graphicsSpecified
        {
            get
            {
                return this.validate_objects_when_selecting_in_graphicsFieldSpecified;
            }
            set
            {
                this.validate_objects_when_selecting_in_graphicsFieldSpecified = value;
                this.RaisePropertyChanged("validate_objects_when_selecting_in_graphicsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool automatic_save_to_backup_copy
        {
            get
            {
                return this.automatic_save_to_backup_copyField;
            }
            set
            {
                this.automatic_save_to_backup_copyField = value;
                this.RaisePropertyChanged("automatic_save_to_backup_copy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool automatic_save_to_backup_copySpecified
        {
            get
            {
                return this.automatic_save_to_backup_copyFieldSpecified;
            }
            set
            {
                this.automatic_save_to_backup_copyFieldSpecified = value;
                this.RaisePropertyChanged("automatic_save_to_backup_copySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool save_after_calculation
        {
            get
            {
                return this.save_after_calculationField;
            }
            set
            {
                this.save_after_calculationField = value;
                this.RaisePropertyChanged("save_after_calculation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool save_after_calculationSpecified
        {
            get
            {
                return this.save_after_calculationFieldSpecified;
            }
            set
            {
                this.save_after_calculationFieldSpecified = value;
                this.RaisePropertyChanged("save_after_calculationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int automatically_save_after
        {
            get
            {
                return this.automatically_save_afterField;
            }
            set
            {
                this.automatically_save_afterField = value;
                this.RaisePropertyChanged("automatically_save_after");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool automatically_save_afterSpecified
        {
            get
            {
                return this.automatically_save_afterFieldSpecified;
            }
            set
            {
                this.automatically_save_afterFieldSpecified = value;
                this.RaisePropertyChanged("automatically_save_afterSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
